## Write script to deploy to EC2 instance
name: Deploy to EC2
on:
  push:
    branches:
      - main
jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY_BACKEND }}
          REMOTE_USER: ubuntu
          REMOTE_HOST: ${{ secrets.EC2_SERVER_IP_BACKEND }}
          TARGET: /home/ubuntu/Quizz-App/dist
          SOURCE: ./dist/
          SCRIPT_BEFORE: |
            pm2 stop all || true
            mkdir -p /home/ubuntu/Quizz-App/logs
            rm -rf /home/ubuntu/Quizz-App/dist
          SCRIPT_AFTER: |
            cd /home/ubuntu/Quizz-App/dist
            npm install --production
            pm2 start all || pm2 start index.js --name "Quizz-App"